### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by yakutovicha** [cheminfo-py/cheminfopy#28]
Currently, the aiidalab-eln tests are failing because cheminfopy with the new changes is not yet released:

<img width="899" alt="Screenshot 2021-07-15 at 16 23 49" src="https://user-images.githubusercontent.com/13118485/125804404-67bdc735-6fcc-447b-a78c-847213f4cb72.png">

**Comment by yakutovicha** [comment]
also, dependabot is getting crazy :D

https://github.com/cheminfo-py/cheminfopy/pulls

**Comment by kjappelbaum** [comment]
thanks, will do it now

**Comment by kjappelbaum** [comment]
Done
